### ISSUE TITLE
Setup:  ERROR: Could not find a version that satisfies the requirement scipy

### ISSUE THREAD

**Issue by jspooner** [carl24k/fight-churn#43]
Hello, I'm currently using Python 3.6.8, and I'm having trouble installing the packages listed in my requirements.txt file. When I run pip install -r requirements.txt, it's not able to find the latest version of many of the packages. To get around this, I've been manually editing the requirements.txt file to specify the versions that are available, but there are a lot of packages with incorrect version numbers.

I've also tried Googling this issue, but I'm not sure why my package manager isn't able to find the latest versions of these packages. Do you have any suggestions for how I can fix this?

Thank you for your help.

```
#8 23.79 ERROR: Could not find a version that satisfies the requirement scipy==1.6.2 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
#8 23.79 ERROR: No matching distribution found for scipy==1.6.2
------
```

```
#8 6.064 ERROR: Could not find a version that satisfies the requirement joblib==1.2.0 (from versions: 0.3.2d.dev, 0.3.2e.dev, 0.3.2f.dev, 0.3.2g.dev, 0.7.0d, 0.1a0.dev0, 0.2a0.dev0, 0.3a0.dev0, 0.3.1a0.dev0, 0.3.2.dev0, 0.3.2a0.dev0, 0.3.2b0.dev0, 0.3.2rc0.dev0, 0.3.3a0.dev0, 0.3.3b0.dev0, 0.3.3rc0.dev0, 0.3.4.dev0, 0.3.5.dev0, 0.3.6.dev0, 0.3.7.dev0, 0.4.0.dev0, 0.4.1.dev0, 0.4.2.dev0, 0.4.3.dev0, 0.4.4.dev0, 0.4.5.dev0, 0.4.6.dev0, 0.5.0.dev0, 0.5.0a0.dev0, 0.5.1.dev0, 0.5.2.dev0, 0.5.3.dev0, 0.5.4.dev0, 0.5.5.dev0, 0.5.6.dev0, 0.5.7.dev0, 0.5.7a0.dev0, 0.5.7b0.dev0, 0.5.7, 0.6.0a0, 0.6.0b0, 0.6.0b2, 0.6.0b3, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0a0, 0.7.0b0, 0.7.0rc0, 0.7.1, 0.8.0a0, 0.8.0a2, 0.8.0a3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.3.post1, 0.8.4, 0.9.0b2, 0.9.0b3, 0.9.0b4, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.2, 0.10.3, 0.11a3, 0.11, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.17.0, 1.0.0, 1.0.1, 1.1.0a0, 1.1.0, 1.1.1)
```

**Comment by jspooner** [comment]
Full output
```
 > [7/8] RUN pip install -r requirements.txt:                                                 
#11 0.707 Collecting bleach==3.3.0                                                            
#11 0.873   Downloading bleach-3.3.0-py2.py3-none-any.whl (283 kB)                            
#11 1.030 Collecting build==0.4.0                                                             
#11 1.070   Downloading build-0.4.0-py2.py3-none-any.whl (14 kB)                              
#11 1.129 Collecting certifi==2020.12.5
#11 1.188   Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
#11 1.405 Collecting chardet==4.0.0
#11 1.445   Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
#11 1.534 Collecting cloudpickle==1.6.0
#11 1.574   Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)
#11 1.642 Collecting colorama==0.4.4
#11 1.681   Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
#11 1.722 Collecting cycler==0.10.0
#11 1.761   Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
#11 1.820 Collecting docutils==0.17.1
#11 1.859   Downloading docutils-0.17.1-py2.py3-none-any.whl (575 kB)
#11 2.330 Collecting greenlet==1.0.0
#11 2.370   Downloading greenlet-1.0.0.tar.gz (84 kB)
#11 2.412   Preparing metadata (setup.py): started
#11 2.675   Preparing metadata (setup.py): finished with status 'done'
#11 2.726 Collecting idna==2.10
#11 2.769   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
#11 2.897 Collecting importlib-metadata==4.5.0
#11 2.936   Downloading importlib_metadata-4.5.0-py3-none-any.whl (17 kB)
#11 3.017 ERROR: Could not find a version that satisfies the requirement joblib==1.2.0 (from versions: 0.3.2d.dev, 0.3.2e.dev, 0.3.2f.dev, 0.3.2g.dev, 0.7.0d, 0.1a0.dev0, 0.2a0.dev0, 0.3a0.dev0, 0.3.1a0.dev0, 0.3.2.dev0, 0.3.2a0.dev0, 0.3.2b0.dev0, 0.3.2rc0.dev0, 0.3.3a0.dev0, 0.3.3b0.dev0, 0.3.3rc0.dev0, 0.3.4.dev0, 0.3.5.dev0, 0.3.6.dev0, 0.3.7.dev0, 0.4.0.dev0, 0.4.1.dev0, 0.4.2.dev0, 0.4.3.dev0, 0.4.4.dev0, 0.4.5.dev0, 0.4.6.dev0, 0.5.0.dev0, 0.5.0a0.dev0, 0.5.1.dev0, 0.5.2.dev0, 0.5.3.dev0, 0.5.4.dev0, 0.5.5.dev0, 0.5.6.dev0, 0.5.7.dev0, 0.5.7a0.dev0, 0.5.7b0.dev0, 0.5.7, 0.6.0a0, 0.6.0b0, 0.6.0b2, 0.6.0b3, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0a0, 0.7.0b0, 0.7.0rc0, 0.7.1, 0.8.0a0, 0.8.0a2, 0.8.0a3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.3.post1, 0.8.4, 0.9.0b2, 0.9.0b3, 0.9.0b4, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.2, 0.10.3, 0.11a3, 0.11, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.17.0, 1.0.0, 1.0.1, 1.1.0a0, 1.1.0, 1.1.1)
#11 3.017 ERROR: No matching distribution found for joblib==1.2.0
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1
```

**Comment by jspooner** [comment]
> Joblib has no mandatory dependencies besides Python (supported versions are 3.7+).

Ah, joblib is only supported in Python 3.7 and it works as expected.

**Comment by jspooner** [comment]
I was unsuccessful at getting this setup. A docker file would be an excellent way to get this set for people that purchase this book.

**Comment by jspooner** [comment]
I have Python 3.9.7 installed, and after 4 hours of waiting for things to compile, it's still not working.

**Comment by carl24k** [comment]
Hi, sorry for the difficulties. Python 3.9.13 is what I seem to have installed. To be honest, I'm a better data scientist than Python devloper ;-)  But I'll try to help! It seems to be complaining about not having something setup for Postgres, called pg_config. Did you already install Postgres?

**Comment by jspooner** [comment]
I'm close to running it, but I switched to Docker to change versions more easily.

I'm using this so far, but I'm getting an error with Postgres.  I'll share the docker setup when I have it all working. 

docker-compose.yml
```
version: '3'
services:
  python:
    build: .
    container_name: python
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      COMPOSE_DOCKER_CLI_BUILD: 1
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=mytoken
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    depends_on:
      - postgres
```

Dockerfile
```
FROM python:3.9.6-bullseye
WORKDIR /app
RUN apt-get update && apt-get install -y \
        python3 python3-dev \
        gcc \
        musl-dev \
        linux-headers-amd64 \
        g++ \
        liblapack-dev \
        gfortran \
        libopenblas-dev \
        libffi-dev libssl-dev
# https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV VIRTUAL_ENV=/app/py_venv
RUN pip install --upgrade setuptools
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./requirements.txt /app
COPY ./fightchurn /app
RUN  python3 -m pip install --use-pep517 --upgrade pip setuptools wheel && \
  python3 -m pip install --use-pep517 -r requirements.txt  && \
  python3 -m pip install --use-pep517 fightchurn

COPY bashrc /root/.bashrc
COPY . /app
CMD ["python3"]
```

**Comment by jspooner** [comment]
docker-compose.yml
```
version: '3'
services:
  python:
    build: .
    container_name: python
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - COMPOSE_DOCKER_CLI_BUILD=1
      - CHURN_DB=mydb
      - CHURN_DB_USER=myuser
      - CHURN_DB_PASS=mysecretpassword
      - CHURN_DB_HOST=postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=mytoken
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    depends_on:
      - postgres
```

Dockerfile
```
FROM python:3.9.6-bullseye
WORKDIR /app
RUN apt-get update && apt-get install -y \
        python3 python3-dev \
        gcc \
        musl-dev \
        linux-headers-amd64 \
        g++ \
        liblapack-dev \
        gfortran \
        libopenblas-dev \
        libffi-dev libssl-dev
# https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV VIRTUAL_ENV=/app/py_venv
RUN pip install --upgrade setuptools
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./requirements.txt /app
COPY ./fightchurn /app
RUN  python3 -m pip install --use-pep517 --upgrade pip setuptools wheel && \
  python3 -m pip install --use-pep517 -r requirements.txt  && \
  python3 -m pip install --use-pep517 fightchurn

COPY bashrc /root/.bashrc
COPY . /app
CMD ["python3"]
```

You have to create a role `CREATE ROLE postgres;`

Then you can run the chrundb.py script.  

```
docker-compose run python  python3 fightchurn/datagen/churndb.py 

Creating schema socialnet7 (if not exists)...
Creating table event (if not exists)
Creating table subscription (if not exists)
Creating table event_type (if not exists)
Creating table metric (if not exists)
Creating table metric_name (if not exists)
Creating table active_period (if not exists)
Creating table observation (if not exists)
Creating table active_week (if not exists)
Creating table account (if not exists)
```

So far it works.  If you want the code, I can submit a PR.  I'm eager to get into the book now 🚀
